# Generated by Django 3.1.3 on 2022-01-10 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_auto_20220110_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='hood_hospital',
            new_name='Hospital_Toll',
        ),
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='hood_police',
            new_name='Police_Toll',
        ),
    ]
